# Generated by Django 3.1 on 2020-12-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectplanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='user_color',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
