# Generated by Django 3.1 on 2020-11-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=280, null=True),
        ),
    ]
