# Generated by Django 3.1 on 2020-11-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectplanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=280, null=True),
        ),
    ]
