# Generated by Django 3.1 on 2020-11-22 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectplanner', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_users',
            field=models.ManyToManyField(blank=True, related_name='project_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
