# Generated by Django 3.1 on 2020-11-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectplanner', '0004_project_project_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='notifications',
        ),
    ]
