# Generated by Django 3.1 on 2020-11-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectplanner', '0004_auto_20201107_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projectplanner.Project'),
        ),
    ]
