# Generated by Django 3.1 on 2020-11-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectplanner', '0005_remove_project_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
