# Generated by Django 3.1 on 2020-11-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectplanner', '0005_auto_20201108_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projectplanner.project'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='completed',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
