# Generated by Django 3.1 on 2020-11-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectplanner', '0007_auto_20201122_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=None),
        ),
    ]
